### ISSUE TITLE
Multiple problem using source files

### ISSUE THREAD

**Issue by benhab-i** [Xeio/WanderLost#112]
Hi, i have tried to launch both of your sources Android Studio / Visual Studio.

Android : if you want gradle to compile you will have to deletes .idea/gradle.xml and .idea/workspaces.xml from your files it prevent gradle to build correctly.

Visual Studio : Impossible to find the Option  "Manage Secrets" when I right click on Server solution. (using VS 2022). Also when I try to launch the solution in debug mode I have an error "The project doesn't know how to run the profile WanderLost.Server" I don't know what I'm doing wrong

Thanks in advance

**Comment by Xeio** [comment]
Should just be this option in Visual Studio
![image](https://user-images.githubusercontent.com/25418/170577617-f76a6942-00f4-455d-bae9-81a7389d562b.png)

Not sure about Android, maybe I should just gitignore the whole .idea folder since I have no idea if the default .gitignore provided by google is actually any good, and basically know nothing about Android Studio.

**Comment by benhab-i** [comment]
Thanks for you fast reply. I forget to add .NET framework during installation of VS... my bad, I have an exception with SQL when i launch the app now. I found the secrets.json file but it's empty.

For Android Studio yeah you could add the folder .idea in gitignore it will work.

**Comment by Xeio** [comment]
Yeah, secrets would be empty by default, you need to generate a discord app like explained [here]( https://github.com/Xeio/WanderLost/blob/main/dev-readme.md) and fill it in to get the authentication process working.
