### ISSUE TITLE
Feature Request: Support for time zones different from server time

### ISSUE THREAD

**Issue by CambionLS** [Xeio/WanderLost#114]
If your local computer time is different from server time, you don't get correct time for vendor spawns. Providing a method to set your local time offset could resolve this.

**Comment by Xeio** [comment]
It should already work like that, what browser/OS are you using that doesn't?

**Comment by CambionLS** [comment]
It doesn't seem to be working for at least one person that I know in the Philippines who plays on Avesta East At, for example, around 8:45pm EDT on his system the Lost Merchants showed something like 9m21s until spawn when in reality the merchants in question were  of course up. I'll ask them to post here with more details but I know he has tried both Edge and Chrome.

**Comment by Xeio** [comment]
Uh, if it's off by minutes rather than hours, then that's probably a problem with the clock on the PC in question not time zones. The browser just uses the system clock to determine spawn times. It already knows how to account for offsets even if your time zone doesn't match the server.

I'd have them check if the windows clock looks correct compared to something like https://time.is/
