### ISSUE TITLE
Feature request: conditional notification cancelling

### ISSUE THREAD

**Issue by Xane48** [Xeio/WanderLost#123]
Pretty simple core idea, disable the notification if you've already upvoted the merchant stock.

For example, I have notifications set to 10 upvotes on Legendary Rapport items. If I submit the merchant stock then it's automatically upvoted, I don't need a notification 5 minutes later when 9 other people go and confirm.

**Comment by Xeio** [comment]
This should at least mostly work now, at least for notifications directly from the site. There's a few cases where you might still get a ding (like if you have thresholds set to zero votes) due to the way notifications trigger before the first vote is technically registered.

Push notifications are a fair bit "dumber" in that they don't have any sort of user identifier associated with the subscription, so there's unlikely to ever be a way to stop those for merchants you submit.
