### ISSUE TITLE
NA servers - wrong merchants due to Daylight Savings Time change

### ISSUE THREAD

**Issue by jzeeGitHub** [Xeio/WanderLost#166]
With the Daylight Savings Time changes for the NA servers, the wrong merchants are showing up on the site

**Comment by jzeeGitHub** [comment]
Nevermind, it seems to be working now!

**Comment by jzeeGitHub** [comment]
Reopening - Depending on the hour, sometimes it's wrong and sometimes it's right

**Comment by OnVoK24** [comment]
Comparing Maxroll merchants hours vs lostmerchants page, yeah, at the moment, they are different,
Can confirm the lostmerchants website have wrong merchants after time change maintance

**Comment by joel-melling** [comment]
NA East - Avesta: Lucas was showing next hour but was available. 11:30 EST

**Comment by Xeio** [comment]
I'm going to assume they just did the opposite of what they did [last time](https://github.com/Xeio/WanderLost/commit/9361770cc5ea4a0942c3542f2b681077e65bbf02). Though I guess change the SA servers according to their blog post.

Sort of wonder if I could put the auto-swap code I originally had back in, I got rid of it because Smilegate had so many issues fixing DST in-game in the spring. Kinda painful that only some servers seem to actually flip for DST though, so I don't know what "time zone" they consider them in.

In any case, site should be fixed now, though you'll need to refresh the page to get the updated timings.
