### ISSUE TITLE
Mearchant list is not correct since today due to summer time

### ISSUE THREAD

**Issue by Chris2011931** [Xeio/WanderLost#186]
Hi, since the time is now summer time (CEST) and not CET anymore, the listed mearchants are not correct anymore.
Currently, the mearchants of the last hour are displayed in the grid.

**Comment by Xeio** [comment]
Should hopefully be fixed now, though you'll need to refresh your browser.

Since I did most of the work to auto-switch based on a time zone for NA a few weeks ago, I just moved the EUW and EUC servers to Europe/London and Europe/Warsaw time zones respectively. Assuming SG/AZG actually swaps them regularly now I shouldn't have to tweak anything later this year.

**Comment by Chris2011931** [comment]
Thank you for fixing the issue so fast and your effort. Just checked it for one mearchant and it seems to work correctly again. Therefore I will close the issue.
