### ISSUE TITLE
Notification not working

### ISSUE THREAD

**Issue by eliezer43** [Xeio/WanderLost#20]
How can I enable notifications? I've enable it already but it is not working, on any of my browsers T-T

**Comment by kehufrog** [comment]
i can attest to notifications not working. no sound no nothing. other sites notification work just fine.

**Comment by Xeio** [comment]
Do the test buttons on the Notifications settings page work at all?

**Comment by imayx** [comment]
At least on Chrome 99.0.4844.84, both the notification settings page and the notifications "button" on the merchant page have no user interactive functions at all.

**Comment by Xeio** [comment]
Hmmm, so you see this:
![disabled](https://user-images.githubusercontent.com/25418/161591212-41c1bddc-8299-478f-8fc0-01597a1b900a.png)

Rather than this when attempting to click the "Notifications" page?
![enabled](https://user-images.githubusercontent.com/25418/161591264-bdec2e7e-a785-4d2a-b60e-29796a3b1578.png)

My guess would be it's a browser-permissions issue. In theory when you click "Merchant Notifications" in the upper right it's supposed to tell the browser to prompt you for the site to get the notifications permission. I could maybe add a warning if the issue is caused by browser permissions.

Just tried on Chrome and the page seems to work for me (I use normally Edge which is Chromium based, so they should behave similarly anyway).

You could try to click this padlock in the URL bar, and see if the browser disabled them, it should look like this in Chrome:
![setting](https://user-images.githubusercontent.com/25418/161591954-4069f7db-0a30-4f28-852d-da2e98ba9bb6.png)

**Comment by imayx** [comment]
Hi, thanks for the detailed instructions - this helped get the interface to show up, but when clicking the "test notifcations" buttons for merchants and items, nothing happens. I've tried various permissions settings (pop-ups, sounds) but nothing seems to work. What does the notification look like when it activates?

**Comment by Xeio** [comment]
So, depends on your OS. 

In Win 11 it looks something like this (and generally does play a sound for me):
![notification](https://user-images.githubusercontent.com/25418/161603184-ae577e31-3d84-474e-80dc-dabca3ce6db9.png)

You can also click the clock to see all the noifications/clear them/change settings as well.

![notif_menu](https://user-images.githubusercontent.com/25418/161603437-b1242faf-d7ef-4dc1-aa7f-21f050cfd46d.png)

Should follow the OS-level settings for how notifications are handled, so sound/popover/ect is controlled by that.

**Comment by kehufrog** [comment]
I had OS notifications disabled, but enabling it worked for me. I think perhaps you should add something that says that notifications are OS-level. Many people have OS notifications disabled because Win10 had a bunch of annoying options and settings and disabled them. Usually these notifications are browser based, so I think this is where the confusion lies for many people.

**Comment by Xeio** [comment]
Alternatively (or in addition) could pull in parts of #18 as an option to the OS-level notifications.
