### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by EinSl** [Xeio/WanderLost#21]
![image](https://user-images.githubusercontent.com/103014177/161670093-6dcbea62-0171-4162-9852-e40f6becc367.png)

Website is not running even though internet connection is fine.

**Comment by EinSl** [comment]
Does anyone know how to solve this issue?

**Comment by Xeio** [comment]
So this isn't strictly a connection issue, note the bar at the bottom of the screen. There's some error happening which is likely causing the whole connection process to abort.

You can try to hit F12 in your browser and open the "Dev tools", in theory it would look something like this:

![Possible Errors](https://user-images.githubusercontent.com/25418/162091964-a7e30eb0-b467-46ea-8e98-e295e4383eb0.png)

I'd need to know what the error(s) are because I can't see those from the server.

**Comment by EinSl** [comment]
I see this when I go to the developer mode:

![image](https://user-images.githubusercontent.com/103014177/162115983-0cc314de-ddca-4d72-93a8-5e17b307d472.png)

I noticed the "display: block;" was highlighted when I refresh the page

**Comment by Xeio** [comment]
So that's close to what I need, I need what's in that panel at the bottom, where all the red-text with a pink-background though it's partially cut off. You can also go to the "Console" tab at the top top make that section full-screen.

Odd thing is it does sort of look like it's a connectivity problem based on what I can see... maybe some issue connecting to the SignalR hub even though you can connect to the website itself (the hub is what does the real-time updates to the browser from other users).

**Comment by EinSl** [comment]
![image](https://user-images.githubusercontent.com/103014177/162130743-b1723083-0355-490f-9f68-db474343632f.png)

Does this work?

**Comment by Xeio** [comment]
Yup, though that's a bit weird since it looks like a DNS lookup failed.

What do you see if you try to go to this URL? Should be a mostly blank page that says connection ID required. 

https://hub.xeio.synology.me/Merchant

**Comment by EinSl** [comment]
Actually it tells me that site cannot be reached.

**Comment by Xeio** [comment]
Ok, so something is wrong with your DNS server, I assume you're just using the default that your ISP provides?

It should be finding something like this:

https://dns-lookup.com/hub.xeio.synology.me

**Comment by EinSl** [comment]
Yeah, sometimes it's working but other times it's not.  Here is a screenshot of the developer page when the site is working: 
![image](https://user-images.githubusercontent.com/103014177/162308536-0ff1637d-c107-45e9-9df8-4014b10e7af5.png)

**Comment by brazc** [comment]
`Firefox can’t establish a connection to the server at wss://hub.xeio.synology.me/MerchantHub.`

**Comment by Xeio** [comment]
Can you let me know if this is working now? Had to flip to the full chain cert to enable that.

**Comment by brazc** [comment]
I enabled OCSP again, will be able to give feedback on this as time passes.

**Comment by AurelienNaveletN** [comment]
I confirm it is working now on firefox.

**Comment by Xeio** [comment]
Sounds good.

Oddly enough can't get SSL stapling to work on the test deployment site which is served from the save nginx instance... but since nobody but me should care about that one I'm just going to close this again, hopefully for good.
