### ISSUE TITLE
Feature Request - Users and Permissions

### ISSUE THREAD

**Issue by kyleshrader** [Xeio/WanderLost#48]
US East > Una got trolled today. SaintBot doesn't have that issue as much because accounts have user IDs. You could have a non-notification suggestion by new users that requires votes. And items like Wei Card could require certain requirements.

Maybe upvotes is a form of account points to show reputation.

**Comment by Cyco0815** [comment]
Yeah this would be nice, having user accounts with a "trusted" state/reputation to verify stuff. But I would make this an optional feature, so that users are still able to suggest and vote anonymously.
@Xeio you mentioned some form of user accounts in the past, is this still something you want? The new database context could be used to store user accounts/identity info.

I'll play around with some authorization this weekend, even if only for my own curiosity. So far my experience with this is limited to server-side blazor, the only time I tried it in a client-side app like this it was a major pain.

**Comment by Xeio** [comment]
I've been playing around with it on a dummy project though didn't have much time over this last weekend to really dig in, mostly trying to figure out which parts I need to directly implement. It's going to require a few server-size razor pages at a minimum for the auth piece I think, though sadly a lot of the ASP Core scaffolld default are a bit overkill for our purposes. Ideally probably only want OAuth logins (probably just a single provider like Discord) instead of direct accounts, and I don't really want/need to collect things like e-mail so use something else as a user key.

May also want to use JWT auth though I think technically we could probably get away with cookie-based auth since the SignalR hub is always hosted on a subdomain. SignalR takes some extra parameters when building the connection to send which should make initializing the connection easy at least... though depending on how we restrict access it may make the login process more complicated because we'd need to redirect a user when they try to send, say, a "Wei" card. Technically we could put an authorization policy directly on the UpdateMerchant hub endpoint that only forces auth for certain inputs... though I don't entirely know if that actually simplifies anything on the client.

So... yeah a few things spinning in my head but I haven't done anything concrete yet.

**Comment by Xeio** [comment]
I push a version of this to https://test.lostmerchants.com if anyone wants to let me know if you have any issues. Should mostly be seamless, just click "Login with Discord" on the toolbar, authorize and it should sign you in and create an account on the backend. Should also keep you signed in normally.

Currently there is no functionality around accounts and I may just push this as-is so it's easier to keep up with main and add individual features. Last thing I might want to do is capture the IP of the user at time of registration for logging purposes.

**Comment by Cyco0815** [comment]
Works as expected 👍
What do I have to do to run this locally? I am using the "authentication-nodefaultui" Branch. I understand that I need to create my own Discord-OAuth2-App thingy and add the ClientSecret and ClientId to appsettings.json. I got it working to the Discord redirect, but now I get an "Invalid OAuth2 redirect_uri" error from the Discord page:
![image](https://user-images.githubusercontent.com/101972110/165506241-da1a1495-ae7f-482e-adcf-52b6e77102cd.png)

Is my redirect wrong, or do I need to make additional changes on Discords' site?
![image](https://user-images.githubusercontent.com/101972110/165506595-9b29701f-f8c1-443c-adbd-f1f1a2e01917.png)

**Comment by Xeio** [comment]
Hmmm, that port is correct? For some reason I though the project was supposed to remember port based on launchSettings.json which is set to 7043.

If that's the correct port you may also need to adjust appsettings.Development.json, specifically this line which tells Identity Server where it "lives". This is mostly for the deployed instances though somaybe I could do this setup step only in non-dev so it's this line wouldn't be necessary.

> "IdentityServerOrigin": "https://localhost:7043",

Probably going to need a small dev-setup.md file here...

**Comment by Cyco0815** [comment]
Setting the redirect port to 7043 did the trick! So it's `https://localhost:7043/signin-discord`.
Some blog said it's supposed to be the ssl port, which obviously it is not in this case. The IdentityServerOrigin is already in the appsettings.Development.json, so I did not need to add it.

**Comment by Xeio** [comment]
Done:

https://github.com/Xeio/WanderLost/blob/main/dev-readme.md
