### ISSUE TITLE
Timezones don't match up with Server Times

### ISSUE THREAD

**Issue by Kvoo** [Xeio/WanderLost#55]
Hey. Just wanted to let you know, the Timezones are actually wrong in the game. It's correct in your tool, but that way it doesn't actually work for tracking the merchants. I'm on EU West, the in-game time right now is 15:50 UTC, while the actual time for that region would be 16:50. My local time (I live in Central Europe) is 17:50. So your tool is 1 hour late. 

Even if that were fixed, many people play on regions in different timezones. Could you implement the possibility to manually set a server-time or just choose UTC+X / UTC-X, which is shown when hovering over the clock in the game? That would make it much more useful, and you wouldn't have to keep adjusting the times then Daylight Savings Time hits.

**Comment by Xeio** [comment]
So the site is already built to run specifically against UTC time. You can see the UTC offsets it uses here, which are region-specific:
https://github.com/Xeio/WanderLost/blob/main/WanderLost/WanderLost/Client/wwwroot/data/servers.json

Is the EU West offset there is incorrect? It matches the in-game tooltip, but I know those have been wrong in the past (and Smilegate seems to not be great at handling time zones to begin with).

It won't help specifically to give individual users a setting, because the server validates all submissions coming in against the expected UTC time of the server.

**Comment by Kvoo** [comment]
Well I‘m in UTC+2 due to daylight savings time. That‘s EU Central. In-Game, EU-Central has UTC+1 because they haven‘t adjusted for DST.

EU-West has UTC+0 In-Game, which would be UTC+1 in real life right now, again, due to daylight savings time. So if you use the real-life time for tracking the merchants, it‘s incorrect because the game itself is off by an hour.

The 2 hours off was just because I live in Central Europe and play on the EU West server, not a failt in your site. But I can just remedy that by using

From my understanding, you‘d have to shift the time in your tool back 1 hour (so 1 hour earlier than the real-life time right now) to be able to sync up with in-game times and track the correct time until the merchant spawns. OR (probably much much easier), just add 1 hour to the shown time until spawn.

As it is right now, when your site shows, for example, Ben spawns in 1 hour on EU West/Central, he actually spawns in 2 hours. I haven‘t looked into the other regions, just europe.

Of course, once daylight saving time is over, you‘d have to revert that change, or make it an automatic process.

________________________________

**Comment by Xeio** [comment]
I haven't touched anything, been looking at it a bit and watching the EUW servers but it seems like people are submitting fine (and upvoting) which makes me think at the minimum it's not the UTC offsets that are the issue.

It's possible the browser got out of sync or something, I have noticed occasional oddities if I flip the server/region dropdowns around a lot and playing with the DST setting on my local machine basically means I have to full-refresh the page, but nothing that seems out of place. Hard to be sure because it could be right for some merchants one hour and wrong the next or something.

**Comment by Kvoo** [comment]
Yeah that could possibly be it! I'll keep trying it out, I'll close this issue for now. 

Thank you for making this tool, by the way :)
