### ISSUE TITLE
Not working correctly for past few days?

### ISSUE THREAD

**Issue by lostarkplayer** [Xeio/WanderLost#97]
I have been using it fine for a week or two. But now I dont seem to get notifications correctly.
I always have the red bar when I first open the page.  Also testing merchant spawn seems to work for me but not test item found. 
I have done all the help steps and still am having problems.
Windows 10/Chrome

**Comment by Xeio** [comment]
Which red bar? The one that tells you to click the page? That one is due to the browser and is normal, you always have to click once after the page loads in order for the site to be able to play sound.

As far as the tests it's strange if only one of the two tests is working. The only real differences between them are the text they display. It's more likely something related Windows (and the focus-assist settings), though normally even that should affect both in the same way.

**Comment by ChengPoh** [comment]
I have been having problems too - Testing notifications on both items and merchant spawns, but only merchant spawns produce sounds. However the popup appears for both.

**Comment by stychu** [comment]
Yeah, I'm having the same problem. No more notifications happening.
I'm not able to even fire off test notifications nor for cards not for reports. 
IM getting some errors in the console. @Xeio 

![brave_cKESbffoRv](https://user-images.githubusercontent.com/9383657/168653687-15e17aa7-f000-4940-9df9-a2fe168a21b0.png)

![brave_4iAvhswolf](https://user-images.githubusercontent.com/9383657/168653707-90e0f50f-eccb-4d31-b417-16dca65ec809.png)

![brave_WBgukWCgJZ](https://user-images.githubusercontent.com/9383657/168653722-0f1a0298-ddcf-489a-91dc-539cae0e1399.png)

**Comment by Xeio** [comment]
Hmmm, so that last red message is my fault, forgot to check that there is a valid Push Subscription before checking if it needs to be updated. Going to deploy a fix for that tonight, though it won't have any other effect than removing the logged error.

You have something odd going on that you don't even have checkboxes though. There should be a check box next to each of "Play sound when matching..." and "Use In-Browser Notifications", so that they are completely blank/missing is... uh... odd.

Somewhat related, it seems like there may be a bug with the "Test Item" button, that it doesn't play the sound and only sends the Notification, whereas the "Test Spawn" button does both sound and notification. This only affects the test button though and as long as "Play sound when matching item found" is checked the sound will still play when a matching item is on the site.

**Comment by stychu** [comment]
> Hmmm, so that last red message is my fault, forgot to check that there is a valid Push Subscription before checking if it needs to be updated. Going to deploy a fix for that tonight, though it won't have any other effect than removing the logged error.
> 
> You have something odd going on that you don't even have checkboxes though. There should be a check box next to each of "Play sound when matching..." and "Use In-Browser Notifications", so that they are completely blank/missing is... uh... odd.
> 
> Somewhat related, it seems like there may be a bug with the "Test Item" button, that it doesn't play the sound and only sends the Notification, whereas the "Test Spawn" button does both sound and notification. This only affects the test button though and as long as "Play sound when matching item found" is checked the sound will still play when a matching item is on the site.

Oh, man, MY bad. I completely missed the checkbox "Use in-browser notifications". I checked this and it works again!

Thanks for great tool!

**Comment by MagicPro1994** [comment]
Can you help me with Firebase config? I tried to build your app but it gave my a critical message on debug "Firebase not configured, skipping message sending. Need 'FirebaseSecretFile' config setting for private key."
Do you have discord or add me via Seijin#8216

**Comment by Xeio** [comment]
You should probably create a separate issue for that, rather than add it to this discussion.
